/*
 * SendingData.java
 * Author : Arakene
 * Created Date : 2020-02-07
 */
package com.thunder_cut.server;

import com.thunder_cut.server.data.DataType;

import java.nio.ByteBuffer;

/**
 * Generate data for send to all client
 */
public class SendingData {

    public final DataType dataType;
    public final int srcID;
    public final int destID;
    public final byte[] data;

    public SendingData(int srcID, int destID, DataType dataType, byte[] data) {
        this.srcID = srcID;
        this.destID = destID;
        this.dataType = dataType;
        this.data = data;
    }

    /**
     * Generate header and attach data
     * Header must promised sequence => dataType(char), srcID(int), destID(int), dataSize(int) and data(byte[])
     * @return generated ByteBuffer with given data
     */
    public ByteBuffer toByteBuffer() {
        ByteBuffer buffer = ByteBuffer.allocate(data.length + 14);
        buffer.putChar(dataType.type);
        buffer.putInt(srcID);
        buffer.putInt(destID);
        buffer.putInt(data.length);
        buffer.put(data);

        buffer.flip();

        return buffer;
    }
}
